### ISSUE TITLE
Mono compatibility

### ISSUE THREAD

**Issue by degloff** [mbraceproject/MBrace.Core#93] opened 2015-06-12 07:33 UTC
Running m-brace on Linux / Mono for heterogeneous clusters.
Getting around issue that Microsoft.ServiceBus library doesn't work on mono as figured out by Konstantinos:

```
#r "Microsoft.ServiceBus"
open Microsoft.ServiceBus
open Microsoft.ServiceBus.Messaging
let ns = NamespaceManager.CreateFromConnectionString("[conn]")
```

In the interactive:

```
System.TypeInitializationException: An exception was thrown by the type initializer for TimerManager ---> System.EntryPointNotFoundException: CreateWaitableTimer

at (wrapper managed-to-native)  Microsoft.ServiceBus.Common.Interop.UnsafeNativeMethods:CreateWaitableTimer (intptr,bool,string)
```

In a compiled binary the Mono runtime just hangs. It looks like the ServiceBus library uses some native libs not available in mono.

**Comment by cgravill** [comment] 2015-09-30 09:22
I’ve checked the current version of Microsoft.ServiceBus.dll, 3.0.3 and it looks the same. This isn’t open sourced yet per:
http://feedback.azure.com/forums/216926-service-bus/suggestions/6948939-open-source-microsoft-servicebus-dll-windowsazure

Other people who’ve run into the Service Bus library compatibility on Linux have suggested using this open source alternative:
https://github.com/ppatierno/azuresblite

I did a small experiment with the code, and it doesn’t look to cover apis that MBrace.Azure uses in Microsoft.ServiceBus.dll.

Any guidance if any of these are worth perusing?

**Comment by palladin** [comment] 2015-09-30 10:16
Even if we have a CoreCLR that runs perfectly on Linux the Serive Bus-Linux combatibility will still be an issue... so yes it is very important to have alternatives. (Btw thanks for azuresblite I didn't know about it)

**Comment by dsyme** [comment] 2017-06-08 13:08
Closing this as dupe of #155

**Closed by dsyme** 2017-06-08 13:08 UTC
Labels: MBrace.Azure
