### ISSUE TITLE
Better Support for Local and Non Azure Setup Options

### ISSUE THREAD

**Issue by sirinath** [mbraceproject/MBrace.Core#110] opened 2015-07-14 20:05 UTC

**Comment by dsyme** [comment] 2015-07-24 12:21
Hi @sirinath, 

I know that @eiriktsarpalis and team are very busy completing the technical details for 1.0

It would be great to have you contribute to the guides!  The current content is at https://github.com/mbraceproject/mbrace-docs/tree/master/docs/content.  Just send a pull request with the updates.

Cheers
Don

**Comment by dsyme** [comment] 2015-07-25 01:18
Treating as duplicate of request #109

**Closed by dsyme** 2015-07-25 01:18 UTC
