### ISSUE TITLE
Nuget packages fail to install

### ISSUE THREAD

**Issue by mathias-brandewinder** [mbraceproject/MBrace.Core#104] opened 2015-06-26 16:04 UTC
VS2013, trying to add MBrace.Azure 0-6-10-alpha via the NuGet extension (right-click add reference) to a fresh F# library project, getting this:
````
Attempting to resolve dependency 'MBrace.Core (= 0.9.12-alpha)'.
Attempting to resolve dependency 'MBrace.Runtime.Core (= 0.9.12-alpha)'.
Attempting to resolve dependency 'Vagabond (= 0.6.9)'.
Attempting to resolve dependency 'Mono.Cecil (= 0.9.6.1)'.
Attempting to resolve dependency 'FsPickler (≥ 1.2.2 && < 1.3.0)'.
Attempting to resolve dependency 'FsPickler.Json'.
Attempting to resolve dependency 'Newtonsoft.Json (≥ 6.0.5 && < 6.1.0)'.
Attempting to resolve dependency 'FsPickler (= 1.2.9)'.
Attempting to resolve dependency 'FsPickler (= 1.2.7)'.
Updating 'FsPickler 1.2.9' to 'FsPickler 1.2.7' failed. Unable to find a version of 'FsPickler.Json' that is compatible with 'FsPickler 1.2.7'.
````

**Comment by eiriktsarpalis** [comment] 2015-06-26 16:12
Ok, so this looks like a paket issue possibly. I do not specify a version for FsPickler.Json in `paket.dependencies` :
```
source https://nuget.org/api/v2

nuget FsPickler 1.2.9
nuget FsPickler.Json
```
and this seems to be carried over to the auto-generated nuspec:
```xml
      <dependency id="FsPickler.Json" version="" />
      <dependency id="FsPickler" version="[1.2.9]" />
```

This looks like a bug. @forki?

**Comment by forki** [comment] 2015-06-26 16:21
Yes you should use => in the dependencies file

**Comment by eiriktsarpalis** [comment] 2015-06-26 16:30
It's not so much about the exact version constraint as it is FsPickler.Json lacking a version number. In this case, paket.lock correctly infers that FsPickler.Json should be [1.2.9] but this information is not carried over to the generated package.

**Comment by eiriktsarpalis** [comment] 2015-06-27 13:30
This has been fixed in MBrace.Core.* 0.9.14. Note that the MBrace.Azure packages will have to be updated accordingly before the issue is resolved there.

**Closed by eiriktsarpalis** 2015-06-27 13:30 UTC

**Comment by forki** [comment] 2015-06-27 13:56
If you think there is something we should change in paket then please open
issue. I think I didn't really understand the problem yet

**Comment by eiriktsarpalis** [comment] 2015-06-27 14:27
@forki done. https://github.com/fsprojects/Paket/issues/905
